spring:
  profiles:
    active: development-cloud
---
spring:
  profiles: development-cloud
  application:
    name: eureka-server  
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${spring.application.name}.eastus2.cloudapp.azure.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: F://application_logs/${spring.application.name}.log
  level:
        org.springframework: 'OFF'   
        com.netflix.eureka: 'OFF'  
        com.netflix.discovery: 'OFF'        
---
spring:
  profiles: cloud
  application:
    name: eureka-server  

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: F://application_logs/${spring.application.name}.log
  level:
        org.springframework: 'OFF'   
        com.netflix.eureka: 'OFF'  
        com.netflix.discovery: 'OFF' 
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/        




