spring:
  profiles:
    active: development-cloud
---
spring:
  profiles: development-cloud
server:
  port: 8761
spring:
  application:
    name: eureka-server

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: F://application_logs/${spring.application.name}.log
  level:
        org.springframework: DEBUG   
        com.netflix.eureka: 'OFF'  
        com.netflix.discovery: 'OFF'        
---
spring:
  profiles: cloud
server:
  port: 8761
spring:
  application:
    name: eureka-server
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: F://application_logs/${spring.application.name}.log
  level:
        org.springframework: DEBUG   
        com.netflix.eureka: 'OFF'  
        com.netflix.discovery: 'OFF' 




