spring:
  profiles:
    active: development-cloud
---
spring:
  profiles: development-cloud
  application:
    name: plm-part-ms  

eureka:
   name:eureka-server
 # vipAddress: ${eureka.name}.eastus2.cloudapp.azure.com
  client:
    serviceUrl:
      defaultZone: http://${eureka.name}:8761/eureka/

logging:
  file: F://application_logs/${spring.application.name}.log
  level:
        org.springframework: DEBUG   
        com.netflix.eureka: 'OFF'  
        com.netflix.discovery: 'OFF'        
---
spring:
  profiles: cloud
  application:
    name: plm-part-ms  

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  file: F://application_logs/${spring.application.name}.log
  level:
        org.springframework: DEBUG   
        com.netflix.eureka: 'OFF'  
        com.netflix.discovery: 'OFF'        